title: Avi Shah
logo: /assets/logo.png
description: >
  <strong style="font-weight: bold; color: #e41919;">Email: avishah704@gmail.com</strong>
  <br>
  <a href="/assets/Resume.pdf" target="_blank">Resume</a>
  <br>
  <a href="https://www.linkedin.com/in/-avishah/" target="_blank">LinkedIn</a>
  <br>
  <a href="https://github.com/avishah3" target="_blank">GitHub</a>
  <br>
  <a href="https://www.effxcts.com/" target="_blank">Effxcts LLC</a>
show_downloads: false
theme: jekyll-theme-minimal
github:
  is_project_page: false
