title: Avi Shah
logo: /assets/logo.png
description: >
  <a href="/assets/Resume.pdf" target="_blank">Resume</a>
  <br>
  <a href="mailto:avishah3@gmail.com">Email (avishah3@gmail.com)</a>
  <br>
  <a href="https://www.linkedin.com/in/-avishah/">LinkedIn</a>
  <br>
  <a href="https://github.com/avishah3">GitHub</a>
  <br>
  <a href="https://www.effxcts.com/">Effxcts LLC</a>
show_downloads: false
theme: jekyll-theme-minimal
github:
  is_project_page: false
